### ISSUE TITLE
Rank is a reserved word in MySQL 8.0.2 onwards

### ISSUE THREAD

**Issue by peterjc** [biosql/biosql#22]
According to https://dev.mysql.com/doc/refman/8.0/en/keywords.html MySQL v8.0.2 made ``RANK`` a reserved word.

BioSQL has a multiple columns named ``rank`` including:
* ``term_dbxref.rank``
* ``bioentry_relationship.rank``
* ``dbxref_qualifier_value .rank``
* ``bioentry_dbxref.rank``
* ``bioentry_reference.rank``
* ``comment.rank``
* ``bioentry_qualifier_value.rank``
* ``seqfeature.rank``
* ``seqfeature_relationship.rank``
* ``seqfeature_qualifier_value.rank``
* ``seqfeature_dbxref.rank``
* ``location.rank``

This means previously valid SQL commands may no longer work.

This was logged in Biopython by @lhovo, this MySQL change broke our loading sequences into the database:

https://github.com/biopython/biopython/issues/1882

It appears we just need to wrap the SQL column name with back-ticks as a work around, so this should not need a schema change in BioSQL itself.

However, it could also affect the BioPerl, BioJava, BioRuby bindings too (perhaps not if they use a more abstracted ORM rather than SQL directly)?

**Comment by peterjc** [comment]
MySQL v8.0.2 was apparently released 2017-07-17
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-2.html

TravisCI currently offers MySQL v5.x (depending on which Ubuntu is used)
https://docs.travis-ci.com/user/database-setup/#mysql

AppVeyor currently offers MySQL 5.7
https://www.appveyor.com/docs/services-databases/#mysql

(This explains why Biopython's continuous integration testing didn't catch this)

**Comment by hlapp** [comment]
Is it backticks, or (which would be more standard) double quotes?

I was going to say it'd be great if we could run some simple CI testing here on the various supported RDBMS platforms (e.g., even only simply running the schema DDL scripts against an RDBMS instance). But apparently that wouldn't even catch (or prove having fixed) the issue here, which is unfortunate.

**Comment by lhovo** [comment]
On a quick google search, you are correct double quotes would be the better option as it will work with other databases other than just mysql
