### ISSUE TITLE
load_ncbi_taxonomy.pl (Can't call method "execute" on an undefined value)

### ISSUE THREAD

**Issue by hmkim** [biosql/biosql#7]
I tried to loading the taxonomy into sqlite3 database. 

 `perl load_ncbi_taxonomy.pl --dbname database --driver SQLite --download --directory db_work`

> Downloading NCBI taxon database to db_work
> Loading NCBI taxon database in db_work:
>         ... retrieving all taxon nodes in the database
>         ... reading in taxon nodes from nodes.dmp
>         ... insert / update / delete taxon nodes
> Can't call method "execute" on an undefined value at load_ncbi_taxonomy.pl line 465.

Can you check it ?

**Comment by ctSkennerton** [comment]
I've seen this before where the script is run on a database that hasn't been populated with tables yet. I ran the following to create an empty database from the right file in the sql directory. Then I reran the script and things worked fine.
```
sqlite3 database < sql/biosqldb-sqlite.sql
```
